USE distribumax;

INSERT INTO provincias (iddepartamento, provincia) VALUES 
(1, 'Chachapoyas'),
(1, 'Bagua'),
(1, 'Bongara'),
(1, 'Condorcanqui'),
(1, 'Luya'),
(1, 'Rodriguez de Mendoza'),
(1, 'Utcubamba'),
(2, 'Huaraz'),
(2, 'Aija'),
(2, 'Antonio Raymondi'),
(2, 'Asuncion'),
(2, 'Bolognesi'),
(2, 'Carhuaz'),
(2, 'Carlos Fermin Fitzcarrald'),
(2, 'Casma'),
(2, 'Corongo'),
(2, 'Huari'),
(2, 'Huarmey'),
(2, 'Huaylas'),
(2, 'Mariscal Luzuriaga'),
(2, 'Ocros'),
(2, 'Pallasca'),
(2, 'Pomabamba'),
(2, 'Recuay'),
(2, 'Santa'),
(2, 'Sihuas'),
(2, 'Yungay'),
(3, 'Abancay'),
(3, 'Andahuaylas'),
(3, 'Antabamba'),
(3, 'Aymaraes'),
(3, 'Cotabambas'),
(3, 'Chincheros'),
(3, 'Grau'),
(4, 'Arequipa'),
(4, 'Camana'),
(4, 'Caraveli'),
(4, 'Castilla'),
(4, 'Caylloma'),
(4, 'Condesuyos'),
(4, 'Islay'),
(4, 'La Union'),
(5, 'Huamanga'),
(5, 'Cangallo'),
(5, 'Huanca Sancos'),
(5, 'Huanta'),
(5, 'La Mar'),
(5, 'Lucanas'),
(5, 'Parinacochas'),
(5, 'Paucar del Sara Sara'),
(5, 'Victor Fajardo'),
(5, 'Vilcas Huaman'),
(6, 'Cajamarca'),
(6, 'Cajabamba'),
(6, 'Celendin'),
(6, 'Chota'),
(6, 'Contumaza'),
(6, 'Cutervo'),
(6, 'Hualgayoc'),
(6, 'Jaen'),
(6, 'San Ignacio'),
(6, 'San Marcos'),
(6, 'San Miguel'),
(6, 'San Pablo'),
(6, 'Santa Cruz'),
(7, 'Prov. Const. del Callao'),
(8, 'Cusco'),
(8, 'Acomayo'),
(8, 'Anta'),
(8, 'Calca'),
(8, 'Canas'),
(8, 'Canchis'),
(8, 'Chumbivilcas'),
(8, 'Espinar'),
(8, 'La Convencion'),
(8, 'Paruro'),
(8, 'Paucartambo'),
(8, 'Quispicanchi'),
(8, 'Urubamba'),
(9, 'Huancavelica'),
(9, 'Acobamba'),
(9, 'Angaraes'),
(9, 'Castrovirreyna'),
(9, 'Churcampa'),
(9, 'Huaytara'),
(9, 'Tayacaja'),
(10, 'Huanuco'),
(10, 'Ambo'),
(10, 'Dos de Mayo'),
(10, 'Huacaybamba'),
(10, 'Huamalies'),
(10, 'Leoncio Prado'),
(10, 'Marañon'),
(10, 'Pachitea'),
(10, 'Puerto Inca'),
(10, 'Lauricocha'),
(10, 'Yarowilca'),
(11, 'Ica'),
(11, 'Nazca'),
(11, 'Chincha'),
(11, 'Palpa'),
(11, 'Pisco'),
(12, 'Huancayo'),
(12, 'Concepcion'),
(12, 'Chanchamayo'),
(12, 'Jauja'),
(12, 'Junin'),
(12, 'Satipo'),
(12, 'Tarma'),
(12, 'Yauli'),
(12, 'Chupaca'),
(13, 'Trujillo'),
(13, 'Ascope'),
(13, 'Bolivar'),
(13, 'Chepen'),
(13, 'Julcan'),
(13, 'Otuzco'),
(13, 'Pacasmayo'),
(13, 'Pataz'),
(13, 'Sanchez Carrion'),
(13, 'Santiago de Chuco'),
(13, 'Gran Chimu'),
(13, 'Viru'),
(14, 'Chiclayo'),
(14, 'Ferreñafe'),
(14, 'Lambayeque'),
(15, 'Lima'),
(15, 'Barranca'),
(15, 'Cajatambo'),
(15, 'Canta'),
(15, 'Cañete'),
(15, 'Huaral'),
(15, 'Huarochiri'),
(15, 'Huaura'),
(15, 'Oyon'),
(15, 'Yauyos'),
(16, 'Maynas'),
(16, 'Alto Amazonas'),
(16, 'Loreto'),
(16, 'Mariscal Ramon Castilla'),
(16, 'Requena'),
(16, 'Ucayali'),
(16, 'Datem del Marañon'),
(16, 'Putumayo'),
(17, 'Tambopata'),
(17, 'Manu'),
(17, 'Tahuamanu'),
(18, 'Mariscal Nieto'),
(18, 'General Sanchez Cerro'),
(18, 'Ilo'),
(19, 'Pasco'),
(19, 'Daniel Alcides Carrion'),
(19, 'Oxapampa'),
(20, 'Piura'),
(20, 'Ayabaca'),
(20, 'Huancabamba'),
(20, 'Morropon'),
(20, 'Paita'),
(20, 'Sullana'),
(20, 'Talara'),
(20, 'Sechura'),
(21, 'Puno'),
(21, 'Azangaro'),
(21, 'Carabaya'),
(21, 'Chucuito'),
(21, 'El Collao'),
(21, 'Huancane'),
(21, 'Lampa'),
(21, 'Melgar'),
(21, 'Moho'),
(21, 'San Antonio de Putina'),
(21, 'San Roman'),
(21, 'Sandia'),
(21, 'Yunguyo'),
(22, 'Moyobamba'),
(22, 'Bellavista'),
(22, 'El Dorado'),
(22, 'Huallaga'),
(22, 'Lamas'),
(22, 'Mariscal Caceres'),
(22, 'Picota'),
(22, 'Rioja'),
(22, 'San Martin'),
(22, 'Tocache'),
(23, 'Tacna'),
(23, 'Candarave'),
(23, 'Jorge Basadre'),
(23, 'Tarata'),
(24, 'Tumbes'),
(24, 'Contralmirante Villar'),
(24, 'Zarumilla'),
(25, 'Coronel Portillo'),
(25, 'Atalaya'),
(25, 'Padre Abad'),
(25, 'Purus');