use distribumax;
INSERT INTO provincias (iddepartamento, provincia) VALUES
(1, 'Chachapoyas'),
(1, 'Bagua'),
(1, 'Bongará'),
(1, 'Condorcanqui'),
(1, 'Luya'),
(1, 'Rodríguez de Mendoza'),
(1, 'Utcubamba'),
(2, 'Huaraz'),
(2, 'Aija'),
(2, 'Antonio Raymondi'),
(2, 'Asunción'),
(2, 'Bolognesi'),
(2, 'Carhuaz'),
(2, 'Carlos Fermín Fitzcarrald'),
(2, 'Casma'),
(2, 'Corongo'),
(2, 'Huaylas'),
(2, 'Huastán'),
(2, 'Huaylas'),
(2, 'María José'),
(2, 'Olleros'),
(2, 'Pallasca'),
(2, 'Pomabamba'),
(2, 'Pucas'),
(2, 'Santa'),
(2, 'Sihuas'),
(2, 'Yungay'),
(3, 'Abancay'),
(3, 'Andahuaylas'),
(3, 'Antabamba'),
(3, 'Cotabambas'),
(3, 'Chincheros'),
(3, 'Grau'),
(3, 'Huinchiri'),
(3, 'Pampachiri'),
(3, 'Talavera'),
(3, 'Turpo'),
(4, 'Arequipa'),
(4, 'Camaná'),
(4, 'Caravelí'),
(4, 'Castilla'),
(4, 'Caylloma'),
(4, 'Islay'),
(4, 'La Unión'),
(5, 'Huamanga'),
(5, 'Cangallo'),
(5, 'Huanca Sancos'),
(5, 'Huanta'),
(5, 'La Mar'),
(5, 'Lucanas'),
(5, 'Parinacochas'),
(5, 'Paucar del Sara Sara'),
(5, 'Sucre'),
(5, 'Vinchos'),
(6, 'Jaén'),
(6, 'San Ignacio'),
(6, 'San José de Lourdes'),
(6, 'San Miguel'),
(6, 'San Pablo'),
(6, 'Santa María de Nieva'),
(7, 'Callao'),
(8, 'Cusco'),
(8, 'Acomayo'),
(8, 'Anta'),
(8, 'Calca'),
(8, 'Canas'),
(8, 'Canchis'),
(8, 'Chumbivilcas'),
(8, 'Espinar'),
(8, 'La Convención'),
(8, 'Paruro'),
(8, 'Paucartambo'),
(8, 'Quispicanchi'),
(8, 'Urubamba'),
(9, 'Huancavelica'),
(9, 'Acobamba'),
(9, 'Angaraes'),
(9, 'Castrovirreyna'),
(9, 'Churcampa'),
(9, 'Huancavelica'),
(9, 'Huaytará'),
(9, 'Tayacaja'),
(10, 'Huánuco'),
(10, 'Ambo'),
(10, 'Dos de Mayo'),
(10, 'Huacaybamba'),
(10, 'Huánuco'),
(10, 'Lauricocha'),
(10, 'Leoncio Prado'),
(10, 'Marañón'),
(10, 'Pachitea'),
(10, 'Puerto Inca'),
(10, 'Yarowilca'),
(11, 'Ica'),
(11, 'Chincha'),
(11, 'Ica'),
(11, 'Nazca'),
(11, 'Palpa'),
(11, 'Pisco'),
(12, 'Junín'),
(12, 'Apata'),
(12, 'Chanchamayo'),
(12, 'Huancayo'),
(12, 'Huancavelica'),
(12, 'Jauja'),
(12, 'Junín'),
(12, 'La Mar'),
(12, 'Marañón'),
(12, 'Pangoa'),
(12, 'San Martín de Pangoa'),
(12, 'Satipo'),
(12, 'Tarma'),
(12, 'Yauli'),
(13, 'La Libertad'),
(13, 'Ascope'),
(13, 'Bolívar'),
(13, 'Chepén'),
(13, 'Gran Chimú'),
(13, 'Julcán'),
(13, 'Otuzco'),
(13, 'Pacasmayo'),
(13, 'Trujillo'),
(13, 'Santiago de Chuco'),
(13, 'Pataz'),
(13, 'Virú'),
(14, 'Lambayeque'),
(14, 'Chiclayo'),
(14, 'Ferreñafe'),
(14, 'Lambayeque'),
(15, 'Lima'),
(15, 'Canta'),
(15, 'Cañete'),
(15, 'Huaral'),
(15, 'Huarochirí'),
(15, 'Lima'),
(15, 'Oyon'),
(15, 'Yauyos'),
(16, 'Loreto'),
(16, 'Alto Nanay'),
(16, 'Fernando Lores'),
(16, 'Iquitos'),
(16, 'Maynas'),
(16, 'Nauta'),
(16, 'Requena'),
(16, 'Ucayali'),
(17, 'Madre de Dios'),
(17, 'Manu'),
(17, 'Madre de Dios'),
(17, 'Tambopata'),
(18, 'Moquegua'),
(18, 'Ilo'),
(18, 'Mariscal Nieto'),
(19, 'Pasco'),
(19, 'Pasco'),
(19, 'Daniel Alcides Carrión'),
(19, 'Oxapampa'),
(20, 'Piura'),
(20, 'Ayabaca'),
(20, 'Huancabamba'),
(20, 'Piura'),
(20, 'Sechura'),
(20, 'Sullana'),
(21, 'Puno'),
(21, 'Azángaro'),
(21, 'Carabaya'),
(21, 'Chucuito'),
(21, 'El Collao'),
(21, 'Huancané'),
(21, 'Lampa'),
(21, 'Melgar'),
(21, 'San Antonio de Putina'),
(21, 'San Román'),
(21, 'Yunguyo'),
(22, 'San Martín'),
(22, 'Bellavista'),
(22, 'El Dorado'),
(22, 'Huallaga'),
(22, 'Lamas'),
(22, 'Moyobamba'),
(22, 'Picota'),
(22, 'Rioja'),
(22, 'San Martín'),
(22, 'Tarapoto'),
(23, 'Tacna'),
(23, 'Candarave'),
(23, 'Jorge Basadre'),
(23, 'Tacna'),
(24, 'Tumbes'),
(24, 'Contralmirante Villar'),
(24, 'Tumbes'),
(25, 'Ucayali'),
(25, 'Atalaya'),
(25, 'Coronel Portillo'),
(25, 'Padre Abad'),
(25, 'Purús');
select * from provincias;